# Generated by Django 5.1.1 on 2024-09-19 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Event",
            new_name="Walk",
        ),
        migrations.RenameField(
            model_name="animal",
            old_name="event",
            new_name="walk",
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("adopted", "Adopted"),
                    ("pending", "Pending"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animals",
                to="shelter.animaltype",
            ),
        ),
    ]
