# Generated by Django 5.1.1 on 2024-09-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0003_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="type",
            field=models.CharField(
                choices=[("cat", "Cat"), ("dog", "Dog"), ("others", "Others")],
                max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name="walk",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameIndex(
            model_name="animal",
            new_name="shelter_ani_type_d229bb_idx",
            old_name="shelter_ani_type_id_bbc4e7_idx",
        ),
        migrations.DeleteModel(
            name="AnimalType",
        ),
    ]
