# Generated by Django 5.1.1 on 2024-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0004_alter_animal_type_alter_walk_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("boy", "Boy"), ("girl", "Girl"), ("unknown", "Unknown")],
                default="unknown",
                max_length=10,
            ),
        ),
    ]
