# Generated by Django 5.1.1 on 2024-09-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0005_animal_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walk",
            name="name",
        ),
    ]
