# Generated by Django 5.1.1 on 2024-09-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0006_remove_walk_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="walk",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="walks",
                to="shelter.animal",
            ),
        ),
    ]
